const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#1A8CFF",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#111111",
    cardForeground: "#FFFFFF",
    primary: "#1A8CFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A1A",
    secondaryForeground: "#CCCCCC",
    muted: "#1A1A1A",
    mutedForeground: "#666666",
    accent: "#FF3B30",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#222222",
    input: "#1A1A1A",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#1A8CFF",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#111111",
    cardForeground: "#FFFFFF",
    primary: "#1A8CFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A1A",
    secondaryForeground: "#CCCCCC",
    muted: "#1A1A1A",
    mutedForeground: "#666666",
    accent: "#FF3B30",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#222222",
    input: "#1A1A1A",
  },
  radius: 12,
};

export default colors;
